"""VALOR 核心基础工具。

包含枚举、货币单位、哈希、canonical JSON 序列化、错误层级与 ID 工具。
本层为纯标准库实现，供所有其他子包复用（Phase 0 交付）。
"""

from .enums import (
    ConfigMode,
    DeliveryMode,
    MigrationClass,
    ParamSource,
    QualityImplementationKind,
    RightsState,
    TerminalState,
    TradeState,
)
from .errors import (
    CANONICALIZATION_ERROR,
    CONFIG_VERSION_UNSUPPORTED,
    COUNTERFACTUAL_INFEASIBLE,
    INFEASIBLE_SECURITY,
    INVALID_HASH,
    INVALID_ID,
    INVALID_RIGHTS,
    INVALID_SCHEMA,
    INVALID_SOURCE_KIND,
    MISSING_EVIDENCE_REF,
    OUT_OF_CERTIFIED_RANGE,
    PROFILE_OUT_OF_CERTIFIED_RANGE,
    UNIT_MISMATCH,
    UNRESOLVED_PARAMETER,
    VALORError,
    CanonicalizationError,
    CommitBindingError,
    ConfigVersionUnsupportedError,
    EntitlementError,
    InvalidHashError,
    InvalidIDError,
    InvalidRightsError,
    InvalidSchemaError,
    InvalidSourceKindError,
)
from .money import CURRENCY_UNIT, assert_unit, Money, to_cu
from .hashing import content_hash, sha256_hex, stable_hash, validate_hash
from .canonical_json import (
    CANONICAL_SCHEMA_VERSION,
    canonical_bytes,
    canonical_dumps,
    canonicalize,
)
from .ids import (
    AssetID,
    AuditorID,
    BuyerID,
    CalibrationID,
    EventID,
    PolicyID,
    RightsID,
    SellerID,
    TransactionID,
    ValorID,
    VersionID,
)
from .reproducibility import (
    build_repro_json,
    build_repro_metadata,
    dependency_lock_hash,
    git_commit,
    git_dirty,
)

__all__ = [
    "ConfigMode",
    "DeliveryMode",
    "MigrationClass",
    "ParamSource",
    "QualityImplementationKind",
    "RightsState",
    "TerminalState",
    "TradeState",
    "CANONICALIZATION_ERROR",
    "CONFIG_VERSION_UNSUPPORTED",
    "COUNTERFACTUAL_INFEASIBLE",
    "INFEASIBLE_SECURITY",
    "INVALID_HASH",
    "INVALID_ID",
    "INVALID_RIGHTS",
    "INVALID_SCHEMA",
    "INVALID_SOURCE_KIND",
    "MISSING_EVIDENCE_REF",
    "OUT_OF_CERTIFIED_RANGE",
    "PROFILE_OUT_OF_CERTIFIED_RANGE",
    "UNIT_MISMATCH",
    "UNRESOLVED_PARAMETER",
    "VALORError",
    "CanonicalizationError",
    "CommitBindingError",
    "ConfigVersionUnsupportedError",
    "EntitlementError",
    "InvalidHashError",
    "InvalidIDError",
    "InvalidRightsError",
    "InvalidSchemaError",
    "InvalidSourceKindError",
    "CURRENCY_UNIT",
    "assert_unit",
    "Money",
    "to_cu",
    "content_hash",
    "sha256_hex",
    "stable_hash",
    "validate_hash",
    "CANONICAL_SCHEMA_VERSION",
    "canonical_bytes",
    "canonical_dumps",
    "canonicalize",
    "AssetID",
    "AuditorID",
    "BuyerID",
    "CalibrationID",
    "EventID",
    "PolicyID",
    "RightsID",
    "SellerID",
    "TransactionID",
    "ValorID",
    "VersionID",
    "build_repro_json",
    "build_repro_metadata",
    "dependency_lock_hash",
    "git_commit",
    "git_dirty",
]
